server:
  port: 8080
spring:
  mail:
    # 指定邮件服务器地址
    host: smtp.163.com
    # 登录账户
    username: 18715838915@163.com
    # 登录密码
    password: GMTFWLGLSUKCCJBB
    # 默认编码
    default-encoding: UTF-8
    # 使用的协议
    protocol: smtp
    # 其他的属性
    properties:
      "mail.smtp.connectiontimeout": 5000
      "mail.smtp.timeout": 3000
      "mail.smtp.writetimeout": 5000
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true
      "mail.smtp.starttls.required": true
chatglm:
  sdk:
    config:
      # 状态；true = 开启、false 关闭
      enable: true
      # 官网地址
      api-host: https://open.bigmodel.cn/
      # 官网申请 https://open.bigmodel.cn/usercenter/apikeys
      api-secret-key: 1ed747a5e448e91fa29e717c187a982f.pqlgo9cH00crpjWk