

spring:
  datasource:
    username: luobd
    password: luoyu666@@
    url: jdbc:mysql://47.108.50.14:3306/luobd?characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver

swagger:
  enabled: true


logging:
  config: classpath:logback-spring.xml
  file:
    path: /tmp/logs/



